name: Unit tests

on: 
  push:
  pull_request:
    branches: [ main ]
    
jobs:
  run_style_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: swe4s
          environment-file: environment.yml
      - run: pycodestyle $(git ls-files "*.py")
  run_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: swe4s
          environment-file: environment.yml
      - run: |
          cd testing/unit_testing
          python -m unittest test_my_utils.py
  run_functional_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: swe4s
          environment-file: environment.yml
      - run: |
          cd testing/functional_testing
          bash test_print_fires.sh
